sudo: required
language: cpp
services:
  - docker

script:
  - docker pull $TARGET
  - docker run -e 'MAKEFLAGS=-j2' $TARGET

env:
  matrix:
    - TARGET=libral/f25-build
    - TARGET=libral/el6-build-static

notifications:
  email: false
